import ClayButton from "@/components/ClayButton";
import type { Metadata } from "next";
import { Comic_Relief, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const comicRelief = Comic_Relief({
  variable: "--font-comic-relief",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "SuperNova - by Infinity Production",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${comicRelief.className} ${comicRelief.variable} antialiased circuit-pattern`}
        style={{ position: "relative" }}
      >
        <header className="fixed inset-x-0 top-3 z-50 pointer-events-none">
          <div className="mx-auto max-w-7xl px-4">
            <nav
              aria-label="Main"
              className={[
                "pointer-events-auto flex items-center justify-between gap-4",
                "rounded-2xl border-4 border-black",
                "bg-white/85 backdrop-blur-sm",
                "shadow-[10px_10px_0_#000]",
                "px-4 sm:px-6 py-3",
                "relative overflow-hidden",
              ].join(" ")}
            >
              <div
                aria-hidden
                className="absolute inset-0 opacity-15 -z-10 halftone-wash"
              />
              <div
                aria-hidden
                className="absolute inset-0 opacity-[.18] -z-10 speed-lines"
              />

              <a
                href="/"
                className="inline-flex items-center gap-2 font-black text-xl sm:text-2xl hover:rotate-[-1deg] transition-transform"
              >
                <img
                  src="/SuperNova.png"
                  alt="SuperNova Logo"
                  className="h-10"
                />
                <span className="inline-block bg-pink px-2 rounded-md border-2 border-black shadow-[3px_3px_0_#000]">
                  SuperNova
                </span>
              </a>

              <ClayButton className="cta-chip !text-black hover:-translate-y-0.5 transition-transform">
                <a href="/student">Let&apos;s Get Started</a>
              </ClayButton>
            </nav>
          </div>
        </header>
        <div id="main" className="pt-[calc(env(safe-area-inset-top,0px)+80px)]">
          {children}
        </div>
      </body>
    </html>
  );
}
